/* 
 * Fortify on Demand Web API Explorer
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = FortifyAPI.Client.SwaggerDateConverter;

namespace FortifyAPI.Model
{
    /// <summary>
    /// Post User Application Access Request
    /// </summary>
    [DataContract]
    public partial class PostUserApplicationAccessRequest :  IEquatable<PostUserApplicationAccessRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostUserApplicationAccessRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PostUserApplicationAccessRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PostUserApplicationAccessRequest" /> class.
        /// </summary>
        /// <param name="ApplicationId">The application id (required).</param>
        public PostUserApplicationAccessRequest(int? ApplicationId = default(int?))
        {
            // to ensure "ApplicationId" is required (not null)
            if (ApplicationId == null)
            {
                throw new InvalidDataException("ApplicationId is a required property for PostUserApplicationAccessRequest and cannot be null");
            }
            else
            {
                this.ApplicationId = ApplicationId;
            }
        }
        
        /// <summary>
        /// The application id
        /// </summary>
        /// <value>The application id</value>
        [DataMember(Name="applicationId", EmitDefaultValue=false)]
        public int? ApplicationId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PostUserApplicationAccessRequest {\n");
            sb.Append("  ApplicationId: ").Append(ApplicationId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PostUserApplicationAccessRequest);
        }

        /// <summary>
        /// Returns true if PostUserApplicationAccessRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of PostUserApplicationAccessRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PostUserApplicationAccessRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ApplicationId == input.ApplicationId ||
                    (this.ApplicationId != null &&
                    this.ApplicationId.Equals(input.ApplicationId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ApplicationId != null)
                    hashCode = hashCode * 59 + this.ApplicationId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
