/* 
 * Fortify on Demand Web API Explorer
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = FortifyAPI.Client.SwaggerDateConverter;

namespace FortifyAPI.Model
{
    /// <summary>
    /// Post Mobile Scan Response
    /// </summary>
    [DataContract]
    public partial class PostMobileScanResponse :  IEquatable<PostMobileScanResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostMobileScanResponse" /> class.
        /// </summary>
        /// <param name="ScanId">The id of the scan that was created.</param>
        public PostMobileScanResponse(int? ScanId = default(int?))
        {
            this.ScanId = ScanId;
        }
        
        /// <summary>
        /// The id of the scan that was created
        /// </summary>
        /// <value>The id of the scan that was created</value>
        [DataMember(Name="scanId", EmitDefaultValue=false)]
        public int? ScanId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PostMobileScanResponse {\n");
            sb.Append("  ScanId: ").Append(ScanId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PostMobileScanResponse);
        }

        /// <summary>
        /// Returns true if PostMobileScanResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of PostMobileScanResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PostMobileScanResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ScanId == input.ScanId ||
                    (this.ScanId != null &&
                    this.ScanId.Equals(input.ScanId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ScanId != null)
                    hashCode = hashCode * 59 + this.ScanId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
